In [1]:
#3 types af arrays
print("---- types of arrays ----")

---- types of arrays ----


In [2]:
#LIST: equivalent to the vector in C
#good for adding items and sorting, lenght is not fixed
# disadvantage: slow for calculations
r= list(range(10000000))
r[:10]  # first 10 elements

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
r.pop(0)  # remove first element
%time r.pop(0)  # time to remove first element

CPU times: total: 15.6 ms
Wall time: 9.34 ms


1

In [4]:
%time r.pop()  # time to remove last element    

CPU times: total: 0 ns
Wall time: 4.05 μs


9999999

In [6]:
# deque (double ended queue) from collections module; mostly like a list, but pop from the beginning is faster
#very fast for adding/removing from both ends
from collections import deque
d= deque(list(range(10000000)))

len(d)
d.append(9999999999999999)
d.popleft()  # remove first element
%time d.popleft()  # time to remove first element

CPU times: total: 0 ns
Wall time: 3.1 μs


1

In [9]:
# when you want to store a particular datatype and do calculations on it, use array module
# and if you know the size of your sata
# arrays: fixed size, using C- level datatypes -> numpy library

import numpy as np
a= np.array(range(20), dtype=np.float64)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [10]:
a+100


array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119.])

In [13]:
%time np.log(a+100)

CPU times: total: 0 ns
Wall time: 37 μs


array([4.60517019, 4.61512052, 4.62497281, 4.63472899, 4.6443909 ,
       4.65396035, 4.66343909, 4.67282883, 4.68213123, 4.69134788,
       4.70048037, 4.7095302 , 4.71849887, 4.72738782, 4.73619845,
       4.74493213, 4.75359019, 4.76217393, 4.77068462, 4.77912349])